### ISSUE TITLE
Error and is there the ability to have a config file

### ISSUE THREAD

**Issue by bonelifer** [wfraser/MusicFS#2]
command used:
```
sudo ./musicfs -v -o allow_other,format="%ext%/%albumartist% - %album% (%year%)/%track% - %artist% - %title%.%ext%" /media/william/Data2/BACKUP/MP3/ ~/MUSIC

```
error:
```use: unknown option `format=%ext%/%albumartist% - %album% (%year%)/%track% - %artist% - %title%.%ext%'```

Is there an ability to create something like ~/.musicfs config file?

**Comment by bonelifer** [comment]
This is a direct copy from the git readme.

**Comment by wfraser** [comment]
Oh, it should be `-o pattern=...`, not `format`. I'll fix the readme.

I suppose I can see how a config file could be useful, if you have a lot of aliases or something. This isn't a project I'm actively working on any more, but if you want to implement it, I'll accept a pull request :)
